// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
        "data": [
          {
            "examterm": "202420",
            "dept": "SOAN",
            "crn": "21222",
            "subject": "ANTH",
            "courseno": "2550",
            "section": "B",
            "examStartDate": "AUG-21-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-21-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ARTC",
            "crn": "20800",
            "subject": "ARTH",
            "courseno": "1101",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ARTC",
            "crn": "21233",
            "subject": "ARTH",
            "courseno": "1201",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BIOL",
            "crn": "20813",
            "subject": "BIOL",
            "courseno": "1902",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "150",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "11:30",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BIOL",
            "crn": "30435",
            "subject": "BIOL",
            "courseno": "2201",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "21:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration With Range"
          },
          {
            "examterm": "202420",
            "dept": "BIOL",
            "crn": "21243",
            "subject": "BIOL",
            "courseno": "3104",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BIT",
            "crn": "21244",
            "subject": "BIT",
            "courseno": "2400",
            "section": "A",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "20081",
            "subject": "BUSI",
            "courseno": "1001",
            "section": "R",
            "examStartDate": "AUG-22-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-22-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "20082",
            "subject": "BUSI",
            "courseno": "1002",
            "section": "R",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "NI 4010",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "30590",
            "subject": "BUSI",
            "courseno": "1800",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "20083",
            "subject": "BUSI",
            "courseno": "2001",
            "section": "R",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "20084",
            "subject": "BUSI",
            "courseno": "2002",
            "section": "R",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "20085",
            "subject": "BUSI",
            "courseno": "2005",
            "section": "R",
            "examStartDate": "AUG-23-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-23-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "NI 4020",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "21246",
            "subject": "BUSI",
            "courseno": "2121",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "TB 236",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "21247",
            "subject": "BUSI",
            "courseno": "2204",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "TB 210",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "30655",
            "subject": "BUSI",
            "courseno": "2208",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "150",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "11:30",
            "bldgRmRows": "NI 4010",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "30658",
            "subject": "BUSI",
            "courseno": "2301",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "21248",
            "subject": "BUSI",
            "courseno": "2401",
            "section": "A",
            "examStartDate": "AUG-22-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-22-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "TB 208",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "30669",
            "subject": "BUSI",
            "courseno": "2501",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "21249",
            "subject": "BUSI",
            "courseno": "2503",
            "section": "R",
            "examStartDate": "AUG-20-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-20-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "AT 102",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "21250",
            "subject": "BUSI",
            "courseno": "2505",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "NN 280",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "20086",
            "subject": "BUSI",
            "courseno": "2601",
            "section": "A",
            "examStartDate": "AUG-21-2024",
            "examStartTime": "14:00",
            "examDuration": "120",
            "examEndDate": "AUG-21-2024",
            "examEndTime": "16:00",
            "bldgRmRows": "AT 101",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "21251",
            "subject": "BUSI",
            "courseno": "2701",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "TB 208",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "20088",
            "subject": "BUSI",
            "courseno": "3001",
            "section": "R",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "NI 3020",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "20089",
            "subject": "BUSI",
            "courseno": "3007",
            "section": "R",
            "examStartDate": "AUG-22-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-22-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "10693",
            "subject": "BUSI",
            "courseno": "3008",
            "section": "R",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NI 4010",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "21252",
            "subject": "BUSI",
            "courseno": "3103",
            "section": "A",
            "examStartDate": "AUG-23-2024",
            "examStartTime": "14:00",
            "examDuration": "120",
            "examEndDate": "AUG-23-2024",
            "examEndTime": "16:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "21254",
            "subject": "BUSI",
            "courseno": "4008",
            "section": "R",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BUSI",
            "crn": "30766",
            "subject": "BUSI",
            "courseno": "4601",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CANS",
            "crn": "21261",
            "subject": "CDNS",
            "courseno": "2301",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "18:00",
            "examDuration": "120",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "20:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "COGS",
            "crn": "21270",
            "subject": "CGSC",
            "courseno": "3601",
            "section": "B",
            "examStartDate": "AUG-22-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-22-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CHEM",
            "crn": "30929",
            "subject": "CHEM",
            "courseno": "1001",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CHEM",
            "crn": "21272",
            "subject": "CHEM",
            "courseno": "1002",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "NN 231",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CHEM",
            "crn": "30959",
            "subject": "CHEM",
            "courseno": "1101",
            "section": "A",
            "examStartDate": "JUL-19-2024",
            "examStartTime": "19:00",
            "examDuration": "180",
            "examEndDate": "Jul-19-2024",
            "examEndTime": "22:00",
            "bldgRmRows": "NN 282",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CHEM",
            "crn": "30971",
            "subject": "CHEM",
            "courseno": "2203",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "NI 4010",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CHEM",
            "crn": "21277",
            "subject": "CHEM",
            "courseno": "2204",
            "section": "A",
            "examStartDate": "AUG-20-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-20-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "AT 101",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CHEM",
            "crn": "21281",
            "subject": "CHEM",
            "courseno": "2208",
            "section": "A",
            "examStartDate": "AUG-20-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-20-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "AT 101",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CIVE",
            "crn": "31056",
            "subject": "CIVE",
            "courseno": "2200",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "HUMM",
            "crn": "20152",
            "subject": "CLCV",
            "courseno": "2305",
            "section": "W",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "10:00",
            "examDuration": "70",
            "examEndDate": "AUG-23-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Within Range"
          },
          {
            "examterm": "202420",
            "dept": "HUMM",
            "crn": "31177",
            "subject": "CLCV",
            "courseno": "2500",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "COMP",
            "crn": "21289",
            "subject": "COMP",
            "courseno": "1006",
            "section": "A",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "14:00",
            "examDuration": "120",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "16:00",
            "bldgRmRows": "NN 231",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "COMP",
            "crn": "21291",
            "subject": "COMP",
            "courseno": "1406",
            "section": "A",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "14:00",
            "examDuration": "120",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "16:00",
            "bldgRmRows": "NN 231",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "COMP",
            "crn": "11199",
            "subject": "COMP",
            "courseno": "1805",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "COMP",
            "crn": "20159",
            "subject": "COMP",
            "courseno": "2401",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "AT 102",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "COMP",
            "crn": "20161",
            "subject": "COMP",
            "courseno": "2402",
            "section": "A",
            "examStartDate": "AUG-23-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "AUG-23-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "AT 101",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "COMP",
            "crn": "20161",
            "subject": "COMP",
            "courseno": "2402",
            "section": "A",
            "examStartDate": "AUG-23-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "AUG-23-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "AT 102",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "COMM",
            "crn": "20883",
            "subject": "COMS",
            "courseno": "1001",
            "section": "S",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "20892",
            "subject": "ECON",
            "courseno": "1001",
            "section": "S",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "150",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "11:30",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "21302",
            "subject": "ECON",
            "courseno": "1002",
            "section": "S",
            "examStartDate": "AUG-20-2024",
            "examStartTime": "19:00",
            "examDuration": "150",
            "examEndDate": "AUG-20-2024",
            "examEndTime": "21:30",
            "bldgRmRows": "AT 101",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "21302",
            "subject": "ECON",
            "courseno": "1002",
            "section": "S",
            "examStartDate": "AUG-20-2024",
            "examStartTime": "19:00",
            "examDuration": "150",
            "examEndDate": "AUG-20-2024",
            "examEndTime": "21:30",
            "bldgRmRows": "AT 102",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "32088",
            "subject": "ECON",
            "courseno": "2020",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "150",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "11:30",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "21303",
            "subject": "ECON",
            "courseno": "2030",
            "section": "A",
            "examStartDate": "AUG-23-2024",
            "examStartTime": "10:00",
            "examDuration": "120",
            "examEndDate": "AUG-23-2024",
            "examEndTime": "16:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Within Range"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "32092",
            "subject": "ECON",
            "courseno": "2102",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "21305",
            "subject": "ECON",
            "courseno": "2103",
            "section": "A",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "14:00",
            "examDuration": "150",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "16:30",
            "bldgRmRows": "TB 202",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "32098",
            "subject": "ECON",
            "courseno": "2210",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "21307",
            "subject": "ECON",
            "courseno": "2220",
            "section": "A",
            "examStartDate": "AUG-21-2024",
            "examStartTime": "19:00",
            "examDuration": "180",
            "examEndDate": "AUG-21-2024",
            "examEndTime": "22:00",
            "bldgRmRows": "AT 102",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "21311",
            "subject": "ECON",
            "courseno": "3509",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "14:00",
            "examDuration": "120",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "16:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "32111",
            "subject": "ECON",
            "courseno": "3602",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "21502",
            "subject": "ECON",
            "courseno": "3880",
            "section": "S",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ECON",
            "crn": "21516",
            "subject": "ECON",
            "courseno": "4602",
            "section": "S",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "SYST",
            "crn": "20903",
            "subject": "ECOR",
            "courseno": "1041",
            "section": "S",
            "examStartDate": "JUL-19-2024",
            "examStartTime": "19:00",
            "examDuration": "150",
            "examEndDate": "Jul-19-2024",
            "examEndTime": "21:30",
            "bldgRmRows": "NN 282",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "SYST",
            "crn": "21314",
            "subject": "ECOR",
            "courseno": "1042",
            "section": "T",
            "examStartDate": "AUG-22-2024",
            "examStartTime": "14:00",
            "examDuration": "120",
            "examEndDate": "AUG-22-2024",
            "examEndTime": "16:00",
            "bldgRmRows": "AT 101",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "SYST",
            "crn": "21314",
            "subject": "ECOR",
            "courseno": "1042",
            "section": "T",
            "examStartDate": "AUG-22-2024",
            "examStartTime": "14:00",
            "examDuration": "120",
            "examEndDate": "AUG-22-2024",
            "examEndTime": "16:00",
            "bldgRmRows": "AT 102",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ELEC",
            "crn": "20911",
            "subject": "ECOR",
            "courseno": "1043",
            "section": "S",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "110.4",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "10:50",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ELEC",
            "crn": "21318",
            "subject": "ECOR",
            "courseno": "1044",
            "section": "T",
            "examStartDate": "AUG-20-2024",
            "examStartTime": "14:00",
            "examDuration": "90",
            "examEndDate": "AUG-20-2024",
            "examEndTime": "15:30",
            "bldgRmRows": "AT 302",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CIVE",
            "crn": "20919",
            "subject": "ECOR",
            "courseno": "1045",
            "section": "S",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "14:00",
            "examDuration": "120",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "16:00",
            "bldgRmRows": "NN 282",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CIVE",
            "crn": "21322",
            "subject": "ECOR",
            "courseno": "1046",
            "section": "T",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "HS 1301",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MAAE",
            "crn": "21326",
            "subject": "ECOR",
            "courseno": "1047",
            "section": "T",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "AT 102",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MAAE",
            "crn": "20933",
            "subject": "ECOR",
            "courseno": "1048",
            "section": "S",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MAAE",
            "crn": "21330",
            "subject": "ECOR",
            "courseno": "1048",
            "section": "T",
            "examStartDate": "AUG-23-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-23-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "HS 1301",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CIVE",
            "crn": "32357",
            "subject": "ECOR",
            "courseno": "2050",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "CIVE",
            "crn": "32373",
            "subject": "ECOR",
            "courseno": "3800",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "FED",
            "crn": "32378",
            "subject": "ECOR",
            "courseno": "4995",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "FED",
            "crn": "21510",
            "subject": "EGEN",
            "courseno": "5303",
            "section": "S",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "TB 210",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ELEC",
            "crn": "32385",
            "subject": "ELEC",
            "courseno": "2501",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ELEC",
            "crn": "21334",
            "subject": "ELEC",
            "courseno": "2507",
            "section": "A",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "19:00",
            "examDuration": "180",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "22:00",
            "bldgRmRows": "AT 102",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ELEC",
            "crn": "21339",
            "subject": "ELEC",
            "courseno": "3509",
            "section": "B",
            "examStartDate": "AUG-23-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-23-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "TB 210",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ELEC",
            "crn": "20948",
            "subject": "ELEC",
            "courseno": "3909",
            "section": "B",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ENGL",
            "crn": "12384",
            "subject": "ENGL",
            "courseno": "1300",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ENGL",
            "crn": "32510",
            "subject": "ENGL",
            "courseno": "2500",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "GEOG",
            "crn": "32570",
            "subject": "ENST",
            "courseno": "1020",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "ARTC",
            "crn": "21364",
            "subject": "FILM",
            "courseno": "1101",
            "section": "C",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "14:00",
            "examDuration": "120",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "16:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BIT",
            "crn": "21392",
            "subject": "ITEC",
            "courseno": "2400",
            "section": "A",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "LAWS",
            "crn": "21399",
            "subject": "LAWS",
            "courseno": "1002",
            "section": "A",
            "examStartDate": "AUG-22-2024",
            "examStartTime": "17:00",
            "examDuration": "60",
            "examEndDate": "AUG-23-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Within Range"
          },
          {
            "examterm": "202420",
            "dept": "LAWS",
            "crn": "33788",
            "subject": "LAWS",
            "courseno": "2202",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "90",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "10:30",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "LAWS",
            "crn": "33801",
            "subject": "LAWS",
            "courseno": "2908",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "90",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "10:30",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MAAE",
            "crn": "33966",
            "subject": "MAAE",
            "courseno": "2300",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MAAE",
            "crn": "13852",
            "subject": "MAAE",
            "courseno": "3400",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "21403",
            "subject": "MATH",
            "courseno": "1005",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "AT 101",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20532",
            "subject": "MATH",
            "courseno": "1007",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20536",
            "subject": "MATH",
            "courseno": "1009",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "TB 236",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20539",
            "subject": "MATH",
            "courseno": "1104",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "AT 102",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20542",
            "subject": "MATH",
            "courseno": "1107",
            "section": "A",
            "examStartDate": "AUG-21-2024",
            "examStartTime": "19:00",
            "examDuration": "180",
            "examEndDate": "AUG-21-2024",
            "examEndTime": "22:00",
            "bldgRmRows": "AT 101",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "21407",
            "subject": "MATH",
            "courseno": "1800",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "34219",
            "subject": "MATH",
            "courseno": "2004",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20546",
            "subject": "MATH",
            "courseno": "2007",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "AT 102",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "34232",
            "subject": "MATH",
            "courseno": "2008",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20548",
            "subject": "MATH",
            "courseno": "2107",
            "section": "A",
            "examStartDate": "AUG-20-2024",
            "examStartTime": "19:00",
            "examDuration": "180",
            "examEndDate": "AUG-20-2024",
            "examEndTime": "22:00",
            "bldgRmRows": "AT 302",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20550",
            "subject": "MATH",
            "courseno": "2108",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 280",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20553",
            "subject": "MATH",
            "courseno": "3101",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 280",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20555",
            "subject": "MATH",
            "courseno": "3107",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 282",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "21409",
            "subject": "MATH",
            "courseno": "3705",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "AT 101",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "BIT",
            "crn": "14339",
            "subject": "NET",
            "courseno": "3012",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "150",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "11:30",
            "bldgRmRows": "NN 231",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "NEUR",
            "crn": "34538",
            "subject": "NEUR",
            "courseno": "1202",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "NEUR",
            "crn": "21423",
            "subject": "NEUR",
            "courseno": "1203",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "NEUR",
            "crn": "14382",
            "subject": "NEUR",
            "courseno": "4306",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PHIL",
            "crn": "34731",
            "subject": "PHIL",
            "courseno": "1550",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "22:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration With Range"
          },
          {
            "examterm": "202420",
            "dept": "PHIL",
            "crn": "15751",
            "subject": "PHIL",
            "courseno": "2001",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PHIL",
            "crn": "21426",
            "subject": "PHIL",
            "courseno": "2001",
            "section": "B",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "11:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Within Range"
          },
          {
            "examterm": "202420",
            "dept": "PHIL",
            "crn": "21428",
            "subject": "PHIL",
            "courseno": "2340",
            "section": "A",
            "examStartDate": "AUG-20-2024",
            "examStartTime": "08:30",
            "examDuration": "180",
            "examEndDate": "AUG-20-2024",
            "examEndTime": "20:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Within Range"
          },
          {
            "examterm": "202420",
            "dept": "PHYS",
            "crn": "20650",
            "subject": "PHYS",
            "courseno": "1004",
            "section": "A",
            "examStartDate": "AUG-21-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-21-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "AT 102",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PHYS",
            "crn": "21436",
            "subject": "PHYS",
            "courseno": "1008",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "TB 208",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PHYS",
            "crn": "21440",
            "subject": "PHYS",
            "courseno": "1902",
            "section": "V",
            "examStartDate": "AUG-22-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-22-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PHYS",
            "crn": "21441",
            "subject": "PHYS",
            "courseno": "2903",
            "section": "R",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "00:01",
            "examDuration": "120",
            "examEndDate": "AUG-23-2024",
            "examEndTime": "23:59",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Within Range"
          },
          {
            "examterm": "202420",
            "dept": "PSCI",
            "crn": "21442",
            "subject": "PSCI",
            "courseno": "1100",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PSCI",
            "crn": "34888",
            "subject": "PSCI",
            "courseno": "2002",
            "section": "A",
            "examStartDate": "JUL-18-2024",
            "examStartTime": "22:00",
            "examDuration": null,
            "examEndDate": "Jul-21-2024",
            "examEndTime": "22:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Range"
          },
          {
            "examterm": "202420",
            "dept": "PSCI",
            "crn": "34942",
            "subject": "PSCI",
            "courseno": "2701",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "35024",
            "subject": "PSYC",
            "courseno": "1001",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "21459",
            "subject": "PSYC",
            "courseno": "1002",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "09:00",
            "examDuration": "150",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "21:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Within Range"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "35037",
            "subject": "PSYC",
            "courseno": "2001",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "35043",
            "subject": "PSYC",
            "courseno": "2301",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "07:00",
            "examDuration": "120",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "23:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration With Range"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "35046",
            "subject": "PSYC",
            "courseno": "2400",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "35048",
            "subject": "PSYC",
            "courseno": "2500",
            "section": "A",
            "examStartDate": "JUL-19-2024",
            "examStartTime": "19:00",
            "examDuration": "120",
            "examEndDate": "Jul-19-2024",
            "examEndTime": "21:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "21462",
            "subject": "PSYC",
            "courseno": "2600",
            "section": "A",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "14:00",
            "examDuration": "60",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "15:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "20672",
            "subject": "PSYC",
            "courseno": "3000",
            "section": "A",
            "examStartDate": "AUG-21-2024",
            "examStartTime": "14:00",
            "examDuration": "60",
            "examEndDate": "AUG-21-2024",
            "examEndTime": "15:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "20674",
            "subject": "PSYC",
            "courseno": "3000",
            "section": "B",
            "examStartDate": "AUG-18-2024",
            "examStartTime": "09:00",
            "examDuration": "120",
            "examEndDate": "AUG-18-2024",
            "examEndTime": "11:00",
            "bldgRmRows": "TB 202",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "21464",
            "subject": "PSYC",
            "courseno": "3402",
            "section": "A",
            "examStartDate": "AUG-21-2024",
            "examStartTime": "18:00",
            "examDuration": "120",
            "examEndDate": "AUG-22-2024",
            "examEndTime": "18:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Within Range"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "35083",
            "subject": "PSYC",
            "courseno": "3403",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "07:00",
            "examDuration": "120",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "23:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration With Range"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "21465",
            "subject": "PSYC",
            "courseno": "3404",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "14:00",
            "examDuration": "120",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "16:00",
            "bldgRmRows": "AT 101",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "PSYC",
            "crn": "35097",
            "subject": "PSYC",
            "courseno": "3604",
            "section": "A",
            "examStartDate": "JUL-20-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-20-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "ON LINE",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "HUMM",
            "crn": "21472",
            "subject": "RELI",
            "courseno": "2736",
            "section": "A",
            "examStartDate": "AUG-21-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-21-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20737",
            "subject": "STAT",
            "courseno": "2507",
            "section": "A",
            "examStartDate": "AUG-21-2024",
            "examStartTime": "19:00",
            "examDuration": "180",
            "examEndDate": "AUG-21-2024",
            "examEndTime": "22:00",
            "bldgRmRows": "NN 231",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20744",
            "subject": "STAT",
            "courseno": "2509",
            "section": "A",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-17-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "TB 210",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20748",
            "subject": "STAT",
            "courseno": "2601",
            "section": "A",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "19:00",
            "examDuration": "120",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "21:00",
            "bldgRmRows": "AT 101",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20752",
            "subject": "STAT",
            "courseno": "2602",
            "section": "A",
            "examStartDate": "AUG-20-2024",
            "examStartTime": "14:00",
            "examDuration": "180",
            "examEndDate": "AUG-20-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "TB 236",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "MATH",
            "crn": "20755",
            "subject": "STAT",
            "courseno": "3503",
            "section": "A",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "19:00",
            "examDuration": "180",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "22:00",
            "bldgRmRows": "TB 236",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "SYST",
            "crn": "21190",
            "subject": "SYSC",
            "courseno": "2004",
            "section": "A",
            "examStartDate": "AUG-21-2024",
            "examStartTime": "14:00",
            "examDuration": "170",
            "examEndDate": "AUG-21-2024",
            "examEndTime": "16:50",
            "bldgRmRows": "ME 3457",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "SYST",
            "crn": "21190",
            "subject": "SYSC",
            "courseno": "2004",
            "section": "A",
            "examStartDate": "AUG-21-2024",
            "examStartTime": "14:00",
            "examDuration": "170",
            "examEndDate": "AUG-21-2024",
            "examEndTime": "16:50",
            "bldgRmRows": "ME 3475",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "SYST",
            "crn": "21497",
            "subject": "SYSC",
            "courseno": "2100",
            "section": "A",
            "examStartDate": "AUG-19-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "AUG-19-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "TB 208",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "SYST",
            "crn": "15362",
            "subject": "SYSC",
            "courseno": "2320",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "SYST",
            "crn": "35560",
            "subject": "SYSC",
            "courseno": "3006",
            "section": "A",
            "examStartDate": "JUL-21-2024",
            "examStartTime": "09:00",
            "examDuration": "180",
            "examEndDate": "Jul-21-2024",
            "examEndTime": "12:00",
            "bldgRmRows": "NN 231",
            "locflag": "N",
            "minmaxrow": null,
            "deferral": "D",
            "examavailability": "Fixed Duration"
          },
          {
            "examterm": "202420",
            "dept": "TSE",
            "crn": "20779",
            "subject": "TSES",
            "courseno": "2305",
            "section": "W",
            "examStartDate": "AUG-17-2024",
            "examStartTime": "10:00",
            "examDuration": "70",
            "examEndDate": "AUG-23-2024",
            "examEndTime": "17:00",
            "bldgRmRows": "ON LINE",
            "locflag": "Y",
            "minmaxrow": null,
            "deferral": "F",
            "examavailability": "Fixed Within Range"
          }
        ]
      }
]